<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cyou.yuanbaomao</groupId>
        <artifactId>yuanbaomao-scaffold-parent</artifactId>
        <version>0.1.2-SNAPSHOT</version>
    </parent>

    <groupId>cyou.yuanbaomao</groupId>
    <artifactId>sellersprite-service</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>sellersprite-service</name>
    <description>SellerSprite Open API 集成服务</description>

    <modules>
        <module>sellersprite-common</module>
        <module>sellersprite-ai</module>
        <module>sellersprite-system</module>
        <module>sellersprite-api</module>
        <module>sellersprite-research</module>
        <module>sellersprite-research-graph</module>
        <module>sellersprite-graph-learning</module>
        <module>sellersprite-server</module>
    </modules>


</project>
