// Generated from SellerSprite official documentation on 2026-07-10.
package com.yuanbaomao.sellersprite.api.client;

import java.util.List;

/**
 * SellerSprite 官方文档生成契约索引，用于覆盖率和注释完整性测试。
 */
public final class GeneratedSellerSpriteContractIndex {

    private static final List<SellerSpriteOperation> OPERATIONS = List.of(
            SellerSpriteOperation.PRODUCT_COMPETITOR_LOOKUP,
            SellerSpriteOperation.PRODUCT_RESEARCH,
            SellerSpriteOperation.PRODUCT_NODE,
            SellerSpriteOperation.ASIN_DETAIL,
            SellerSpriteOperation.ASIN_COUPON_TREND,
            SellerSpriteOperation.ASIN_WITH_COUPON_TREND,
            SellerSpriteOperation.ASIN_SALES_TREND,
            SellerSpriteOperation.ASIN_SALES_PREDICTION,
            SellerSpriteOperation.BSR_SALES_PREDICTION,
            SellerSpriteOperation.ASIN_KEEPA_TREND,
            SellerSpriteOperation.KEYWORD_RESEARCH,
            SellerSpriteOperation.KEYWORD_RESEARCH_TRENDS,
            SellerSpriteOperation.KEYWORD_MINER,
            SellerSpriteOperation.KEYWORD_TRAFFIC_EXTEND,
            SellerSpriteOperation.ABA_RESEARCH_WEEKLY,
            SellerSpriteOperation.ABA_RESEARCH_MONTHLY,
            SellerSpriteOperation.ABA_RESEARCH_TRENDS,
            SellerSpriteOperation.GOOGLE_TRENDS,
            SellerSpriteOperation.KEYWORD_ORDER,
            SellerSpriteOperation.TRAFFIC_KEYWORD,
            SellerSpriteOperation.TRAFFIC_LISTING_PAGE,
            SellerSpriteOperation.TRAFFIC_KEYWORD_STAT,
            SellerSpriteOperation.TRAFFIC_LISTING_STAT,
            SellerSpriteOperation.TRAFFIC_SOURCE,
            SellerSpriteOperation.MARKET_RESEARCH,
            SellerSpriteOperation.MARKET_STATISTICS,
            SellerSpriteOperation.MARKET_GOODS,
            SellerSpriteOperation.MARKET_BRAND,
            SellerSpriteOperation.MARKET_SELLER_LOCATION,
            SellerSpriteOperation.MARKET_SELLER,
            SellerSpriteOperation.MARKET_SELLER_TYPE,
            SellerSpriteOperation.MARKET_PERFORMANCE,
            SellerSpriteOperation.MARKET_SHELF_TIME,
            SellerSpriteOperation.MARKET_SHELF_TREND,
            SellerSpriteOperation.MARKET_RATINGS,
            SellerSpriteOperation.MARKET_RATING,
            SellerSpriteOperation.MARKET_PRICE,
            SellerSpriteOperation.MARKET_EBC,
            SellerSpriteOperation.REVIEW_LIST,
            SellerSpriteOperation.OCR,
            SellerSpriteOperation.GLOBAL_BRAND_RANGE,
            SellerSpriteOperation.GLOBAL_BRAND_DETAIL,
            SellerSpriteOperation.GLOBAL_BRAND_LIST,
            SellerSpriteOperation.GLOBAL_BRAND_STATS);

    private static final List<Class<?>> MODEL_TYPES = List.of(
            com.yuanbaomao.sellersprite.api.common.model.dto.SortOrder.class,
            com.yuanbaomao.sellersprite.api.common.model.vo.SellerSpritePageVo.class,
            com.yuanbaomao.sellersprite.api.common.model.vo.BadgeVo.class,
            com.yuanbaomao.sellersprite.api.common.model.vo.SubcategoryVo.class,
            com.yuanbaomao.sellersprite.api.common.model.vo.ProductSummaryVo.class,
            com.yuanbaomao.sellersprite.api.common.model.vo.VariationVo.class,
            com.yuanbaomao.sellersprite.api.common.model.vo.NumericTrendPointVo.class,
            com.yuanbaomao.sellersprite.api.common.model.vo.StringTrendPointVo.class,
            com.yuanbaomao.sellersprite.api.common.model.vo.SubRankTrendVo.class,
            com.yuanbaomao.sellersprite.api.product.model.dto.CompetitorLookupRequest.class,
            com.yuanbaomao.sellersprite.api.product.model.vo.CompetitorLookupVo.class,
            com.yuanbaomao.sellersprite.api.product.model.dto.ProductResearchRequest.class,
            com.yuanbaomao.sellersprite.api.product.model.vo.ProductResearchVo.class,
            com.yuanbaomao.sellersprite.api.product.model.dto.ProductNodeRequest.class,
            com.yuanbaomao.sellersprite.api.product.model.vo.ProductNodeVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.dto.AsinDetailRequest.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinDetailVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.dto.AsinCouponTrendRequest.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinCouponTrendVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.dto.AsinWithCouponTrendRequest.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinWithCouponTrendVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinWithCouponTrendVo.AsinVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinWithCouponTrendVo.CouponTrendsVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.dto.AsinSalesTrendRequest.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinSalesTrendVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinSalesTrendVo.AsinVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinSalesTrendVo.SalesTrendPointsVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.dto.AsinSalesPredictionRequest.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinSalesPredictionVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinSalesPredictionVo.AsinDetailVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinSalesPredictionVo.DailyItemListVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.AsinSalesPredictionVo.MonthItemListVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.dto.BsrSalesPredictionRequest.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.BsrSalesPredictionVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.BsrSalesPredictionVo.ItemListVo.class,
            com.yuanbaomao.sellersprite.api.asin.model.dto.KeepaTrendRequest.class,
            com.yuanbaomao.sellersprite.api.asin.model.vo.KeepaTrendVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.dto.KeywordResearchRequest.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordResearchItemVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordResearchItemVo.SearchDepartmentsVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordResearchItemVo.RelationAsinListVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordResearchItemVo.AraAsinListVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordResearchVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.dto.KeywordResearchTrendRequest.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordResearchTrendVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.dto.KeywordMinerRequest.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordMinerItemVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordMinerItemVo.DepartmentsVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordMinerVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.dto.TrafficKeywordExtendRequest.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.TrafficKeywordExtendItemVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.TrafficKeywordExtendItemVo.RelationVariationsItemsVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.TrafficKeywordExtendVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.dto.AbaWeeklyResearchRequest.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.AbaWeeklyResearchItemVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.AbaWeeklyResearchItemVo.Top3AsinDtoListVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.AbaWeeklyResearchVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.dto.AbaMonthlyResearchRequest.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.AbaMonthlyResearchItemVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.AbaMonthlyResearchItemVo.Top3AsinDtoListVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.AbaMonthlyResearchVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.dto.AbaKeywordTrendRequest.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.AbaKeywordTrendVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.dto.GoogleTrendRequest.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.GoogleTrendVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.GoogleTrendVo.ItemsVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.dto.KeywordOrderRequest.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordOrderItemVo.class,
            com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordOrderVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.dto.TrafficKeywordRequest.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficKeywordVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficKeywordVo.ItemsVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficKeywordVo.ItemsRankPositionVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficKeywordVo.ItemsAdPositionVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficKeywordVo.StatsVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.dto.RelatedTrafficRequest.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.RelatedTrafficVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.dto.TrafficKeywordStatRequest.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficKeywordStatVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficKeywordStatVo.BadgeCountVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.dto.TrafficListingStatRequest.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficListingStatVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficListingStatVo.ItemsVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.dto.TrafficSourceRequest.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficSourceItemVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficSourceItemVo.AsinInfoVo.class,
            com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficSourceVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketResearchRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketResearchItemVo.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketResearchItemVo.Top10ImagesVo.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketResearchVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketStatisticsRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketStatisticsVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketGoodsConcentrationRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketGoodsConcentrationVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketBrandConcentrationRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketBrandConcentrationVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketSellerLocationRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketSellerLocationVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketSellerConcentrationRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketSellerConcentrationVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketSellerTypeRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketSellerTypeVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketDemandTrendRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketDemandTrendVo.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketDemandTrendVo.ItemsVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketShelfTimeRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketShelfTimeVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketShelfTrendRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketShelfTrendVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketRatingsDistributionRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketRatingsDistributionVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketRatingDistributionRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketRatingDistributionVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketPriceDistributionRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketPriceDistributionVo.class,
            com.yuanbaomao.sellersprite.api.market.model.dto.MarketEbcDistributionRequest.class,
            com.yuanbaomao.sellersprite.api.market.model.vo.MarketEbcDistributionVo.class,
            com.yuanbaomao.sellersprite.api.review.model.dto.ReviewListRequest.class,
            com.yuanbaomao.sellersprite.api.review.model.vo.ReviewListItemVo.class,
            com.yuanbaomao.sellersprite.api.review.model.vo.ReviewListVo.class,
            com.yuanbaomao.sellersprite.api.tool.model.dto.OcrRequest.class,
            com.yuanbaomao.sellersprite.api.tool.model.vo.OcrVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkRangeVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.dto.TrademarkDetailRequest.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.LogosVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.AppealsVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.EventsVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.GoodsServicesClassificationVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.MarkDescriptionDetailsVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.MarkDisclaimerDetailsVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.NationalGoodsServicesClassificationVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.PrioritiesVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.PublicationsVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.QcVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.ReferenceVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.ReferenceApplicationVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.ReferenceRegistrationVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.WordMarkSpecificationVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.WordMarkSpecificationMarkTranslationVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.WordMarkSpecificationMarkVerbalElementVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkDetailVo.WordMarkSpecificationMarkSignificantVerbalElementVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.dto.TrademarkListRequest.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkListItemVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkListItemVo.ApplicantsVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkListItemVo.ApplicantsFullAddressVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkListItemVo.ApplicantsFullNameVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkListItemVo.LogosVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkListVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.dto.TrademarkStatsRequest.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkStatsVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkStatsVo.OfficeVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkStatsVo.BrandNameVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkStatsVo.StatusVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkStatsVo.ApplicantVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkStatsVo.NiceClassVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkStatsVo.ApplicationYearVo.class,
            com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkStatsVo.ExpiryYearVo.class);

    private static final List<OfficialExample> OFFICIAL_EXAMPLES = List.of(
            new OfficialExample(SellerSpriteOperation.PRODUCT_COMPETITOR_LOOKUP, "/sellersprite/examples/product_competitor_lookup.json", com.yuanbaomao.sellersprite.api.product.model.vo.CompetitorLookupVo.class, false),
            new OfficialExample(SellerSpriteOperation.PRODUCT_RESEARCH, "/sellersprite/examples/product_research.json", com.yuanbaomao.sellersprite.api.product.model.vo.ProductResearchVo.class, false),
            new OfficialExample(SellerSpriteOperation.PRODUCT_NODE, "/sellersprite/examples/product_node.json", com.yuanbaomao.sellersprite.api.product.model.vo.ProductNodeVo.class, true),
            new OfficialExample(SellerSpriteOperation.ASIN_DETAIL, "/sellersprite/examples/asin_detail.json", com.yuanbaomao.sellersprite.api.asin.model.vo.AsinDetailVo.class, false),
            new OfficialExample(SellerSpriteOperation.ASIN_COUPON_TREND, "/sellersprite/examples/asin_coupon_trend.json", com.yuanbaomao.sellersprite.api.asin.model.vo.AsinCouponTrendVo.class, true),
            new OfficialExample(SellerSpriteOperation.ASIN_WITH_COUPON_TREND, "/sellersprite/examples/asin_with_coupon_trend.json", com.yuanbaomao.sellersprite.api.asin.model.vo.AsinWithCouponTrendVo.class, false),
            new OfficialExample(SellerSpriteOperation.ASIN_SALES_TREND, "/sellersprite/examples/asin_sales_trend.json", com.yuanbaomao.sellersprite.api.asin.model.vo.AsinSalesTrendVo.class, false),
            new OfficialExample(SellerSpriteOperation.ASIN_SALES_PREDICTION, "/sellersprite/examples/asin_sales_prediction.json", com.yuanbaomao.sellersprite.api.asin.model.vo.AsinSalesPredictionVo.class, false),
            new OfficialExample(SellerSpriteOperation.BSR_SALES_PREDICTION, "/sellersprite/examples/bsr_sales_prediction.json", com.yuanbaomao.sellersprite.api.asin.model.vo.BsrSalesPredictionVo.class, false),
            new OfficialExample(SellerSpriteOperation.ASIN_KEEPA_TREND, "/sellersprite/examples/asin_keepa_trend.json", com.yuanbaomao.sellersprite.api.asin.model.vo.KeepaTrendVo.class, false),
            new OfficialExample(SellerSpriteOperation.KEYWORD_RESEARCH, "/sellersprite/examples/keyword_research.json", com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordResearchVo.class, false),
            new OfficialExample(SellerSpriteOperation.KEYWORD_RESEARCH_TRENDS, "/sellersprite/examples/keyword_research_trends.json", com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordResearchTrendVo.class, true),
            new OfficialExample(SellerSpriteOperation.KEYWORD_MINER, "/sellersprite/examples/keyword_miner.json", com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordMinerVo.class, false),
            new OfficialExample(SellerSpriteOperation.KEYWORD_TRAFFIC_EXTEND, "/sellersprite/examples/keyword_traffic_extend.json", com.yuanbaomao.sellersprite.api.keyword.model.vo.TrafficKeywordExtendVo.class, false),
            new OfficialExample(SellerSpriteOperation.ABA_RESEARCH_WEEKLY, "/sellersprite/examples/aba_research_weekly.json", com.yuanbaomao.sellersprite.api.keyword.model.vo.AbaWeeklyResearchVo.class, false),
            new OfficialExample(SellerSpriteOperation.ABA_RESEARCH_MONTHLY, "/sellersprite/examples/aba_research_monthly.json", com.yuanbaomao.sellersprite.api.keyword.model.vo.AbaMonthlyResearchVo.class, false),
            new OfficialExample(SellerSpriteOperation.ABA_RESEARCH_TRENDS, "/sellersprite/examples/aba_research_trends.json", com.yuanbaomao.sellersprite.api.keyword.model.vo.AbaKeywordTrendVo.class, true),
            new OfficialExample(SellerSpriteOperation.GOOGLE_TRENDS, "/sellersprite/examples/google_trends.json", com.yuanbaomao.sellersprite.api.keyword.model.vo.GoogleTrendVo.class, false),
            new OfficialExample(SellerSpriteOperation.KEYWORD_ORDER, "/sellersprite/examples/keyword_order.json", com.yuanbaomao.sellersprite.api.keyword.model.vo.KeywordOrderVo.class, false),
            new OfficialExample(SellerSpriteOperation.TRAFFIC_KEYWORD, "/sellersprite/examples/traffic_keyword.json", com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficKeywordVo.class, false),
            new OfficialExample(SellerSpriteOperation.TRAFFIC_LISTING_PAGE, "/sellersprite/examples/traffic_listing_page.json", com.yuanbaomao.sellersprite.api.traffic.model.vo.RelatedTrafficVo.class, false),
            new OfficialExample(SellerSpriteOperation.TRAFFIC_KEYWORD_STAT, "/sellersprite/examples/traffic_keyword_stat.json", com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficKeywordStatVo.class, false),
            new OfficialExample(SellerSpriteOperation.TRAFFIC_LISTING_STAT, "/sellersprite/examples/traffic_listing_stat.json", com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficListingStatVo.class, false),
            new OfficialExample(SellerSpriteOperation.TRAFFIC_SOURCE, "/sellersprite/examples/traffic_source.json", com.yuanbaomao.sellersprite.api.traffic.model.vo.TrafficSourceVo.class, false),
            new OfficialExample(SellerSpriteOperation.MARKET_RESEARCH, "/sellersprite/examples/market_research.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketResearchVo.class, false),
            new OfficialExample(SellerSpriteOperation.MARKET_STATISTICS, "/sellersprite/examples/market_statistics.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketStatisticsVo.class, false),
            new OfficialExample(SellerSpriteOperation.MARKET_GOODS, "/sellersprite/examples/market_goods.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketGoodsConcentrationVo.class, true),
            new OfficialExample(SellerSpriteOperation.MARKET_BRAND, "/sellersprite/examples/market_brand.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketBrandConcentrationVo.class, true),
            new OfficialExample(SellerSpriteOperation.MARKET_SELLER_LOCATION, "/sellersprite/examples/market_seller_location.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketSellerLocationVo.class, true),
            new OfficialExample(SellerSpriteOperation.MARKET_SELLER, "/sellersprite/examples/market_seller.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketSellerConcentrationVo.class, true),
            new OfficialExample(SellerSpriteOperation.MARKET_SELLER_TYPE, "/sellersprite/examples/market_seller_type.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketSellerTypeVo.class, true),
            new OfficialExample(SellerSpriteOperation.MARKET_SHELF_TIME, "/sellersprite/examples/market_shelf_time.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketShelfTimeVo.class, true),
            new OfficialExample(SellerSpriteOperation.MARKET_SHELF_TREND, "/sellersprite/examples/market_shelf_trend.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketShelfTrendVo.class, true),
            new OfficialExample(SellerSpriteOperation.MARKET_RATINGS, "/sellersprite/examples/market_ratings.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketRatingsDistributionVo.class, true),
            new OfficialExample(SellerSpriteOperation.MARKET_RATING, "/sellersprite/examples/market_rating.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketRatingDistributionVo.class, true),
            new OfficialExample(SellerSpriteOperation.MARKET_PRICE, "/sellersprite/examples/market_price.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketPriceDistributionVo.class, true),
            new OfficialExample(SellerSpriteOperation.MARKET_EBC, "/sellersprite/examples/market_ebc.json", com.yuanbaomao.sellersprite.api.market.model.vo.MarketEbcDistributionVo.class, true),
            new OfficialExample(SellerSpriteOperation.GLOBAL_BRAND_RANGE, "/sellersprite/examples/global_brand_range.json", com.yuanbaomao.sellersprite.api.trademark.model.vo.TrademarkRangeVo.class, true));

    private GeneratedSellerSpriteContractIndex() {
    }

    public static List<SellerSpriteOperation> getOperations() {
        return OPERATIONS;
    }

    public static List<Class<?>> getModelTypes() {
        return MODEL_TYPES;
    }

    public static int getDocumentedRequestFieldCount() {
        return 529;
    }

    public static int getDocumentedResponseFieldCount() {
        return 1197;
    }

    public static List<OfficialExample> getOfficialExamples() {
        return OFFICIAL_EXAMPLES;
    }

    /**
     * 官方响应示例与强类型 data 模型的对应关系。
     *
     * @param operation SellerSprite 操作
     * @param resourcePath classpath 下的官方响应示例
     * @param dataType data 字段的元素或对象类型
     * @param collection data 是否为数组
     */
    public record OfficialExample(SellerSpriteOperation operation, String resourcePath,
                                  Class<?> dataType, boolean collection) {
    }
}
