USE `sellersprite_service`;

-- 来源：spring-batch-core 6.0.4 的 org/springframework/batch/core/schema-mysql.sql。
-- 仅增加 IF NOT EXISTS，便于项目手工迁移脚本重复执行；字段与约束保持官方定义。

CREATE TABLE IF NOT EXISTS `BATCH_JOB_INSTANCE` (
  `JOB_INSTANCE_ID` bigint NOT NULL PRIMARY KEY,
  `VERSION` bigint,
  `JOB_NAME` varchar(100) NOT NULL,
  `JOB_KEY` varchar(32) NOT NULL,
  CONSTRAINT `JOB_INST_UN` UNIQUE (`JOB_NAME`, `JOB_KEY`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION` (
  `JOB_EXECUTION_ID` bigint NOT NULL PRIMARY KEY,
  `VERSION` bigint,
  `JOB_INSTANCE_ID` bigint NOT NULL,
  `CREATE_TIME` datetime(6) NOT NULL,
  `START_TIME` datetime(6) DEFAULT NULL,
  `END_TIME` datetime(6) DEFAULT NULL,
  `STATUS` varchar(10),
  `EXIT_CODE` varchar(2500),
  `EXIT_MESSAGE` varchar(2500),
  `LAST_UPDATED` datetime(6),
  CONSTRAINT `JOB_INST_EXEC_FK` FOREIGN KEY (`JOB_INSTANCE_ID`)
    REFERENCES `BATCH_JOB_INSTANCE` (`JOB_INSTANCE_ID`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION_PARAMS` (
  `JOB_EXECUTION_ID` bigint NOT NULL,
  `PARAMETER_NAME` varchar(100) NOT NULL,
  `PARAMETER_TYPE` varchar(100) NOT NULL,
  `PARAMETER_VALUE` varchar(2500),
  `IDENTIFYING` char(1) NOT NULL,
  CONSTRAINT `JOB_EXEC_PARAMS_FK` FOREIGN KEY (`JOB_EXECUTION_ID`)
    REFERENCES `BATCH_JOB_EXECUTION` (`JOB_EXECUTION_ID`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `BATCH_STEP_EXECUTION` (
  `STEP_EXECUTION_ID` bigint NOT NULL PRIMARY KEY,
  `VERSION` bigint NOT NULL,
  `STEP_NAME` varchar(100) NOT NULL,
  `JOB_EXECUTION_ID` bigint NOT NULL,
  `CREATE_TIME` datetime(6) NOT NULL,
  `START_TIME` datetime(6) DEFAULT NULL,
  `END_TIME` datetime(6) DEFAULT NULL,
  `STATUS` varchar(10),
  `COMMIT_COUNT` bigint,
  `READ_COUNT` bigint,
  `FILTER_COUNT` bigint,
  `WRITE_COUNT` bigint,
  `READ_SKIP_COUNT` bigint,
  `WRITE_SKIP_COUNT` bigint,
  `PROCESS_SKIP_COUNT` bigint,
  `ROLLBACK_COUNT` bigint,
  `EXIT_CODE` varchar(2500),
  `EXIT_MESSAGE` varchar(2500),
  `LAST_UPDATED` datetime(6),
  CONSTRAINT `JOB_EXEC_STEP_FK` FOREIGN KEY (`JOB_EXECUTION_ID`)
    REFERENCES `BATCH_JOB_EXECUTION` (`JOB_EXECUTION_ID`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `BATCH_STEP_EXECUTION_CONTEXT` (
  `STEP_EXECUTION_ID` bigint NOT NULL PRIMARY KEY,
  `SHORT_CONTEXT` varchar(2500) NOT NULL,
  `SERIALIZED_CONTEXT` text,
  CONSTRAINT `STEP_EXEC_CTX_FK` FOREIGN KEY (`STEP_EXECUTION_ID`)
    REFERENCES `BATCH_STEP_EXECUTION` (`STEP_EXECUTION_ID`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION_CONTEXT` (
  `JOB_EXECUTION_ID` bigint NOT NULL PRIMARY KEY,
  `SHORT_CONTEXT` varchar(2500) NOT NULL,
  `SERIALIZED_CONTEXT` text,
  CONSTRAINT `JOB_EXEC_CTX_FK` FOREIGN KEY (`JOB_EXECUTION_ID`)
    REFERENCES `BATCH_JOB_EXECUTION` (`JOB_EXECUTION_ID`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `BATCH_STEP_EXECUTION_SEQ` (
  `ID` bigint NOT NULL,
  `UNIQUE_KEY` char(1) NOT NULL,
  CONSTRAINT `UNIQUE_KEY_UN` UNIQUE (`UNIQUE_KEY`)
) ENGINE=InnoDB;

INSERT INTO `BATCH_STEP_EXECUTION_SEQ` (`ID`, `UNIQUE_KEY`)
SELECT * FROM (SELECT 0 AS `ID`, '0' AS `UNIQUE_KEY`) AS `tmp`
WHERE NOT EXISTS (SELECT * FROM `BATCH_STEP_EXECUTION_SEQ`);

CREATE TABLE IF NOT EXISTS `BATCH_JOB_EXECUTION_SEQ` (
  `ID` bigint NOT NULL,
  `UNIQUE_KEY` char(1) NOT NULL,
  CONSTRAINT `UNIQUE_KEY_UN` UNIQUE (`UNIQUE_KEY`)
) ENGINE=InnoDB;

INSERT INTO `BATCH_JOB_EXECUTION_SEQ` (`ID`, `UNIQUE_KEY`)
SELECT * FROM (SELECT 0 AS `ID`, '0' AS `UNIQUE_KEY`) AS `tmp`
WHERE NOT EXISTS (SELECT * FROM `BATCH_JOB_EXECUTION_SEQ`);

CREATE TABLE IF NOT EXISTS `BATCH_JOB_INSTANCE_SEQ` (
  `ID` bigint NOT NULL,
  `UNIQUE_KEY` char(1) NOT NULL,
  CONSTRAINT `UNIQUE_KEY_UN` UNIQUE (`UNIQUE_KEY`)
) ENGINE=InnoDB;

INSERT INTO `BATCH_JOB_INSTANCE_SEQ` (`ID`, `UNIQUE_KEY`)
SELECT * FROM (SELECT 0 AS `ID`, '0' AS `UNIQUE_KEY`) AS `tmp`
WHERE NOT EXISTS (SELECT * FROM `BATCH_JOB_INSTANCE_SEQ`);
