USE `sellersprite_service`;

CREATE TABLE IF NOT EXISTS `market_research_job` (
  `job_id` char(36) NOT NULL COMMENT '市场调研任务ID，UUIDv7',
  `user_id` char(36) NOT NULL COMMENT '任务归属用户ID',
  `report_name` varchar(128) NOT NULL COMMENT '报告名称',
  `marketplace` varchar(16) NOT NULL DEFAULT 'US' COMMENT 'Amazon站点，第一版固定US',
  `keyword` varchar(256) NOT NULL COMMENT '核心调研关键词',
  `seed_asins` longtext DEFAULT NULL COMMENT '可选种子ASIN数组JSON，最多20个',
  `template_code` varchar(64) NOT NULL DEFAULT 'market-research-v1' COMMENT 'Excel模板代码',
  `data_source_mode` varchar(16) NOT NULL DEFAULT 'MOCK' COMMENT '数据源模式：MOCK REMOTE',
  `job_status` varchar(32) NOT NULL DEFAULT 'QUEUED' COMMENT '任务状态：QUEUED RUNNING SUCCEEDED FAILED',
  `current_phase` varchar(64) NOT NULL DEFAULT 'VALIDATE' COMMENT '当前Batch业务阶段',
  `progress` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '任务进度，0到100',
  `batch_job_instance_id` bigint DEFAULT NULL COMMENT 'Spring Batch JobInstance ID',
  `batch_job_execution_id` bigint DEFAULT NULL COMMENT 'Spring Batch JobExecution ID',
  `error_code` varchar(64) NOT NULL DEFAULT '' COMMENT '稳定业务错误码',
  `error_message` varchar(512) NOT NULL DEFAULT '' COMMENT '可安全展示的错误摘要',
  `started_at` bigint unsigned DEFAULT NULL COMMENT '任务开始时间，Unix毫秒',
  `finished_at` bigint unsigned DEFAULT NULL COMMENT '任务结束时间，Unix毫秒',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`job_id`),
  KEY `idx_market_research_job_user_created` (`user_id`, `created_at`),
  KEY `idx_market_research_job_user_status` (`user_id`, `job_status`),
  KEY `idx_market_research_job_status_updated` (`job_status`, `updated_at`),
  KEY `idx_market_research_job_batch_execution` (`batch_job_execution_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='市场调研Batch任务表';

CREATE TABLE IF NOT EXISTS `market_research_snapshot` (
  `snapshot_id` char(36) NOT NULL COMMENT '采集快照ID，UUIDv7',
  `job_id` char(36) NOT NULL COMMENT '市场调研任务ID',
  `phase` varchar(64) NOT NULL COMMENT '产生快照的Batch业务阶段',
  `operation` varchar(64) NOT NULL COMMENT '采集操作编码',
  `business_key` varchar(256) NOT NULL DEFAULT '' COMMENT '分页或ASIN等业务去重键',
  `data_source_mode` varchar(16) NOT NULL COMMENT '数据源模式：MOCK REMOTE',
  `request_payload` longtext DEFAULT NULL COMMENT '脱敏后的请求参数JSON',
  `response_payload` longtext NOT NULL COMMENT '采集响应JSON',
  `record_count` int unsigned NOT NULL DEFAULT 0 COMMENT '快照包含的顶层业务记录数',
  `sha256` char(64) NOT NULL COMMENT '响应内容SHA-256十六进制摘要',
  `fetched_at` bigint unsigned NOT NULL COMMENT '数据采集时间，Unix毫秒',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`snapshot_id`),
  UNIQUE KEY `uk_market_research_snapshot_key`
    (`job_id`, `phase`, `operation`, `business_key`, `deleted`),
  KEY `idx_market_research_snapshot_job_created` (`job_id`, `created_at`),
  KEY `idx_market_research_snapshot_sha256` (`sha256`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='市场调研采集快照表';

CREATE TABLE IF NOT EXISTS `market_research_artifact` (
  `artifact_id` char(36) NOT NULL COMMENT '报告产物ID，UUIDv7',
  `job_id` char(36) NOT NULL COMMENT '市场调研任务ID',
  `file_name` varchar(255) NOT NULL COMMENT '下载文件名',
  `storage_key` varchar(1024) NOT NULL COMMENT '受控存储键，不是公开URL',
  `media_type` varchar(128) NOT NULL DEFAULT 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' COMMENT '文件媒体类型',
  `file_size` bigint unsigned NOT NULL DEFAULT 0 COMMENT '文件大小，字节',
  `sha256` char(64) DEFAULT NULL COMMENT '文件SHA-256十六进制摘要，草稿生成前为空',
  `artifact_status` varchar(32) NOT NULL DEFAULT 'GENERATING' COMMENT '产物状态：GENERATING PUBLISHED FAILED',
  `published_at` bigint unsigned DEFAULT NULL COMMENT '发布时间，Unix毫秒',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`artifact_id`),
  UNIQUE KEY `uk_market_research_artifact_job` (`job_id`, `deleted`),
  KEY `idx_market_research_artifact_status` (`artifact_status`, `updated_at`),
  KEY `idx_market_research_artifact_sha256` (`sha256`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='市场调研Excel产物表';
