CREATE DATABASE IF NOT EXISTS `sellersprite_service`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE `sellersprite_service`;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` char(36) NOT NULL COMMENT '用户ID，UUIDv7',
  `username` varchar(64) NOT NULL COMMENT '用户名',
  `password_hash` varchar(255) NOT NULL COMMENT '密码哈希',
  `nickname` varchar(64) NOT NULL DEFAULT '' COMMENT '昵称',
  `real_name` varchar(64) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `avatar_url` varchar(512) NOT NULL DEFAULT '' COMMENT '头像地址',
  `mobile` varchar(32) DEFAULT NULL COMMENT '手机号',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `gender` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '性别：0未知 1男 2女',
  `primary_dept_id` char(36) DEFAULT NULL COMMENT '主部门ID',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `last_login_at` bigint unsigned DEFAULT NULL COMMENT '最后登录时间，Unix毫秒',
  `password_updated_at` bigint unsigned DEFAULT NULL COMMENT '密码更新时间，Unix毫秒',
  `permission_version` bigint unsigned NOT NULL DEFAULT 0 COMMENT '权限版本，授权变更时递增',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `uk_user_username` (`username`, `deleted`),
  UNIQUE KEY `uk_user_mobile` (`mobile`, `deleted`),
  UNIQUE KEY `uk_user_email` (`email`, `deleted`),
  KEY `idx_user_primary_dept_id` (`primary_dept_id`),
  KEY `idx_user_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS `dept` (
  `dept_id` char(36) NOT NULL COMMENT '部门ID，UUIDv7',
  `parent_id` char(36) NOT NULL DEFAULT '0' COMMENT '父部门ID，0表示根节点',
  `dept_code` varchar(64) NOT NULL COMMENT '部门编码',
  `dept_name` varchar(128) NOT NULL COMMENT '部门名称',
  `dept_path` varchar(1024) NOT NULL DEFAULT '/' COMMENT '部门路径',
  `leader_user_id` char(36) DEFAULT NULL COMMENT '负责人用户ID',
  `phone` varchar(32) NOT NULL DEFAULT '' COMMENT '联系电话',
  `email` varchar(128) NOT NULL DEFAULT '' COMMENT '邮箱',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序值',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`dept_id`),
  UNIQUE KEY `uk_dept_code` (`dept_code`, `deleted`),
  KEY `idx_dept_parent_id` (`parent_id`),
  KEY `idx_dept_leader_user_id` (`leader_user_id`),
  KEY `idx_dept_status_sort` (`status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='部门表';

CREATE TABLE IF NOT EXISTS `role` (
  `role_id` char(36) NOT NULL COMMENT '角色ID，UUIDv7',
  `role_code` varchar(64) NOT NULL COMMENT '角色编码',
  `role_name` varchar(128) NOT NULL COMMENT '角色名称',
  `role_type` varchar(32) NOT NULL DEFAULT 'BUSINESS' COMMENT '角色类型：SYSTEM系统 BUSINESS业务 CUSTOM自定义',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序值',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`role_id`),
  UNIQUE KEY `uk_role_code` (`role_code`, `deleted`),
  KEY `idx_role_status_sort` (`status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色表';

CREATE TABLE IF NOT EXISTS `user_role` (
  `user_role_id` char(36) NOT NULL COMMENT '用户角色ID，UUIDv7',
  `user_id` char(36) NOT NULL COMMENT '用户ID',
  `role_id` char(36) NOT NULL COMMENT '角色ID',
  `dept_id` char(36) NOT NULL COMMENT '角色所属部门ID',
  `primary_role` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否主角色：1是 0否',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`user_role_id`),
  UNIQUE KEY `uk_user_role` (`user_id`, `role_id`, `dept_id`, `deleted`),
  KEY `idx_user_role_user_id` (`user_id`),
  KEY `idx_user_role_role_id` (`role_id`),
  KEY `idx_user_role_dept_id` (`dept_id`),
  KEY `idx_user_role_primary` (`user_id`, `dept_id`, `primary_role`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户角色表';

CREATE TABLE IF NOT EXISTS `sys_function` (
  `sys_function_id` char(36) NOT NULL COMMENT '系统功能ID，UUIDv7',
  `parent_id` char(36) NOT NULL DEFAULT '0' COMMENT '父功能ID，0表示根节点',
  `function_code` varchar(128) NOT NULL COMMENT '功能编码',
  `function_name` varchar(128) NOT NULL COMMENT '功能名称',
  `function_type` varchar(16) NOT NULL COMMENT '功能类型：DIR目录 MENU菜单 BUTTON按钮',
  `route_path` varchar(255) DEFAULT NULL COMMENT '前端路由路径',
  `component_path` varchar(255) DEFAULT NULL COMMENT '前端组件路径',
  `permission_code` varchar(128) DEFAULT NULL COMMENT '权限标识',
  `icon` varchar(128) NOT NULL DEFAULT '' COMMENT '图标',
  `visible` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '是否可见：1是 0否',
  `cacheable` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否缓存：1是 0否',
  `external_link` varchar(512) DEFAULT NULL COMMENT '外链地址',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序值',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`sys_function_id`),
  UNIQUE KEY `uk_sys_function_code` (`function_code`, `deleted`),
  KEY `idx_sys_function_parent_id` (`parent_id`),
  KEY `idx_sys_function_permission_code` (`permission_code`),
  KEY `idx_sys_function_type_status_sort` (`function_type`, `status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统功能表';

CREATE TABLE IF NOT EXISTS `sys_api` (
  `sys_api_id` char(36) NOT NULL COMMENT '系统接口ID，UUIDv7',
  `api_code` varchar(128) NOT NULL COMMENT '接口编码',
  `api_name` varchar(128) NOT NULL COMMENT '接口名称',
  `api_type` varchar(16) NOT NULL COMMENT '接口类型：PUBLIC公开接口 PERMISSION权限接口',
  `http_method` varchar(16) NOT NULL COMMENT 'HTTP方法',
  `path_pattern` varchar(255) NOT NULL COMMENT '接口路径模式',
  `permission_code` varchar(128) DEFAULT NULL COMMENT '权限标识',
  `module_name` varchar(64) NOT NULL DEFAULT '' COMMENT '模块名称',
  `operation_name` varchar(64) NOT NULL DEFAULT '' COMMENT '操作名称',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`sys_api_id`),
  UNIQUE KEY `uk_sys_api_code` (`api_code`, `deleted`),
  UNIQUE KEY `uk_sys_api_method_path` (`http_method`, `path_pattern`, `deleted`),
  KEY `idx_sys_api_type_status` (`api_type`, `status`),
  KEY `idx_sys_api_permission_code` (`permission_code`),
  KEY `idx_sys_api_module_name` (`module_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统接口表';

CREATE TABLE IF NOT EXISTS `role_function` (
  `role_function_id` char(36) NOT NULL COMMENT '角色功能ID，UUIDv7',
  `role_id` char(36) NOT NULL COMMENT '角色ID',
  `sys_function_id` char(36) NOT NULL COMMENT '系统功能ID',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`role_function_id`),
  UNIQUE KEY `uk_role_function` (`role_id`, `sys_function_id`, `deleted`),
  KEY `idx_role_function_role_id` (`role_id`),
  KEY `idx_role_function_sys_function_id` (`sys_function_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色功能表';

CREATE TABLE IF NOT EXISTS `function_api` (
  `function_api_id` char(36) NOT NULL COMMENT '功能接口关联ID，UUIDv7',
  `sys_function_id` char(36) NOT NULL COMMENT '系统功能ID',
  `sys_api_id` char(36) NOT NULL COMMENT '系统接口ID',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`function_api_id`),
  UNIQUE KEY `uk_function_api` (`sys_function_id`, `sys_api_id`, `deleted`),
  KEY `idx_function_api_function_id` (`sys_function_id`),
  KEY `idx_function_api_api_id` (`sys_api_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='功能接口关联表';

CREATE TABLE IF NOT EXISTS `role_api` (
  `role_api_id` char(36) NOT NULL COMMENT '角色接口ID，UUIDv7',
  `role_id` char(36) NOT NULL COMMENT '角色ID',
  `sys_api_id` char(36) NOT NULL COMMENT '系统接口ID',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`role_api_id`),
  UNIQUE KEY `uk_role_api` (`role_id`, `sys_api_id`, `deleted`),
  KEY `idx_role_api_role_id` (`role_id`),
  KEY `idx_role_api_sys_api_id` (`sys_api_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色接口表';

CREATE TABLE IF NOT EXISTS `dict_type` (
  `dict_type_id` char(36) NOT NULL COMMENT '字典类型ID，UUIDv7',
  `dict_code` varchar(64) NOT NULL COMMENT '字典编码',
  `dict_name` varchar(128) NOT NULL COMMENT '字典名称',
  `system_builtin` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否系统内置：1是 0否',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序值',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`dict_type_id`),
  UNIQUE KEY `uk_dict_type_code` (`dict_code`, `deleted`),
  KEY `idx_dict_type_status_sort` (`status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典类型表';

CREATE TABLE IF NOT EXISTS `dict_item` (
  `dict_item_id` char(36) NOT NULL COMMENT '字典值ID，UUIDv7',
  `dict_type_id` char(36) NOT NULL COMMENT '字典类型ID',
  `item_label` varchar(128) NOT NULL COMMENT '字典标签',
  `item_value` varchar(128) NOT NULL COMMENT '字典值',
  `css_class` varchar(64) NOT NULL DEFAULT '' COMMENT 'CSS类名',
  `color` varchar(32) NOT NULL DEFAULT '' COMMENT '展示颜色',
  `system_builtin` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否系统内置：1是 0否',
  `default_item` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否默认项：1是 0否',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序值',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`dict_item_id`),
  UNIQUE KEY `uk_dict_item_value` (`dict_type_id`, `item_value`, `deleted`),
  KEY `idx_dict_item_type_id` (`dict_type_id`),
  KEY `idx_dict_item_status_sort` (`status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='字典值表';

CREATE TABLE IF NOT EXISTS `user_token` (
  `user_token_id` char(36) NOT NULL COMMENT '用户令牌ID，UUIDv7',
  `user_id` char(36) NOT NULL COMMENT '用户ID',
  `access_token_hash` char(64) NOT NULL COMMENT '访问令牌哈希，建议SHA-256',
  `refresh_token_hash` char(64) DEFAULT NULL COMMENT '刷新令牌哈希，建议SHA-256',
  `session_family_id` char(36) NOT NULL COMMENT '刷新会话链ID，UUIDv7',
  `replaced_by_token_id` char(36) DEFAULT NULL COMMENT '轮换后的令牌ID',
  `token_type` varchar(32) NOT NULL DEFAULT 'BEARER' COMMENT '令牌类型',
  `device_id` varchar(128) DEFAULT NULL COMMENT '设备ID',
  `device_name` varchar(128) NOT NULL DEFAULT '' COMMENT '设备名称',
  `client_type` varchar(32) NOT NULL DEFAULT 'WEB' COMMENT '客户端类型：WEB APP MINI_PROGRAM API',
  `login_ip` varchar(64) NOT NULL DEFAULT '' COMMENT '登录IP',
  `user_agent` varchar(512) NOT NULL DEFAULT '' COMMENT '用户代理',
  `issued_at` bigint unsigned NOT NULL COMMENT '签发时间，Unix毫秒',
  `expires_at` bigint unsigned NOT NULL COMMENT '过期时间，Unix毫秒',
  `refresh_expires_at` bigint unsigned NOT NULL COMMENT '刷新令牌过期时间，Unix毫秒',
  `last_used_at` bigint unsigned DEFAULT NULL COMMENT '最近刷新时间，Unix毫秒',
  `revoked_at` bigint unsigned DEFAULT NULL COMMENT '撤销时间，Unix毫秒',
  `revoke_reason` varchar(256) NOT NULL DEFAULT '' COMMENT '撤销原因',
  `status` tinyint unsigned NOT NULL DEFAULT 1 COMMENT '状态：1有效 0失效',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`user_token_id`),
  UNIQUE KEY `uk_user_token_access_hash` (`access_token_hash`),
  UNIQUE KEY `uk_user_token_refresh_hash` (`refresh_token_hash`),
  KEY `idx_user_token_user_id` (`user_id`),
  KEY `idx_user_token_family_id` (`session_family_id`),
  KEY `idx_user_token_replaced_by` (`replaced_by_token_id`),
  KEY `idx_user_token_expires_at` (`expires_at`),
  KEY `idx_user_token_refresh_expires_at` (`refresh_expires_at`),
  KEY `idx_user_token_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户令牌表';

CREATE TABLE IF NOT EXISTS `login_log` (
  `login_log_id` char(36) NOT NULL COMMENT '登录日志ID，UUIDv7',
  `user_id` char(36) DEFAULT NULL COMMENT '用户ID',
  `username` varchar(64) NOT NULL DEFAULT '' COMMENT '用户名',
  `login_type` varchar(32) NOT NULL DEFAULT 'PASSWORD' COMMENT '登录方式：PASSWORD TOKEN SSO',
  `success` tinyint unsigned NOT NULL COMMENT '是否成功：1成功 0失败',
  `error_code` varchar(64) NOT NULL DEFAULT '' COMMENT '稳定错误码',
  `failure_reason` varchar(512) NOT NULL DEFAULT '' COMMENT '失败原因',
  `login_ip` varchar(64) NOT NULL DEFAULT '' COMMENT '登录IP',
  `login_location` varchar(128) NOT NULL DEFAULT '' COMMENT '登录地点',
  `user_agent` varchar(512) NOT NULL DEFAULT '' COMMENT '用户代理',
  `device_name` varchar(128) NOT NULL DEFAULT '' COMMENT '设备名称',
  `client_type` varchar(32) NOT NULL DEFAULT 'WEB' COMMENT '客户端类型',
  `track_id` varchar(64) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  PRIMARY KEY (`login_log_id`),
  KEY `idx_login_log_user_id` (`user_id`),
  KEY `idx_login_log_username` (`username`),
  KEY `idx_login_log_created_at` (`created_at`),
  KEY `idx_login_log_track_id` (`track_id`),
  KEY `idx_login_log_success` (`success`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='登录日志表';

CREATE TABLE IF NOT EXISTS `operation_log` (
  `operation_log_id` char(36) NOT NULL COMMENT '操作日志ID，UUIDv7',
  `user_id` char(36) DEFAULT NULL COMMENT '用户ID',
  `username` varchar(64) NOT NULL DEFAULT '' COMMENT '用户名',
  `module_name` varchar(64) NOT NULL DEFAULT '' COMMENT '模块名称',
  `operation_name` varchar(128) NOT NULL DEFAULT '' COMMENT '操作名称',
  `operation_type` varchar(32) NOT NULL DEFAULT '' COMMENT '操作类型：CREATE UPDATE DELETE QUERY EXPORT IMPORT',
  `resource_id` varchar(128) NOT NULL DEFAULT '' COMMENT '业务资源ID',
  `http_method` varchar(16) NOT NULL DEFAULT '' COMMENT 'HTTP方法',
  `request_uri` varchar(512) NOT NULL DEFAULT '' COMMENT '请求URI',
  `request_params` json DEFAULT NULL COMMENT '请求参数',
  `response_payload` json DEFAULT NULL COMMENT '响应结果',
  `response_status` int DEFAULT NULL COMMENT '响应状态码',
  `success` tinyint unsigned NOT NULL COMMENT '是否成功：1成功 0失败',
  `error_code` varchar(64) NOT NULL DEFAULT '' COMMENT '稳定错误码',
  `error_message` text DEFAULT NULL COMMENT '错误信息',
  `client_ip` varchar(64) NOT NULL DEFAULT '' COMMENT '客户端IP',
  `user_agent` varchar(512) NOT NULL DEFAULT '' COMMENT '用户代理',
  `cost_ms` bigint unsigned NOT NULL DEFAULT 0 COMMENT '耗时毫秒',
  `track_id` varchar(64) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  PRIMARY KEY (`operation_log_id`),
  KEY `idx_operation_log_user_id` (`user_id`),
  KEY `idx_operation_log_username` (`username`),
  KEY `idx_operation_log_created_at` (`created_at`),
  KEY `idx_operation_log_track_id` (`track_id`),
  KEY `idx_operation_log_module` (`module_name`),
  KEY `idx_operation_log_operation_type` (`operation_type`),
  KEY `idx_operation_log_success` (`success`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志表';

CREATE TABLE IF NOT EXISTS `SPRING_AI_CHAT_MEMORY` (
  `conversation_id` varchar(36) NOT NULL,
  `content` text NOT NULL,
  `type` enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL') NOT NULL,
  `timestamp` timestamp NOT NULL,
  `sequence_id` bigint NOT NULL,
  KEY `SPRING_AI_CHAT_MEMORY_CONVERSATION_ID_TIMESTAMP_IDX` (`conversation_id`, `timestamp`),
  KEY `SPRING_AI_CHAT_MEMORY_CONVERSATION_ID_SEQUENCE_ID_IDX` (`conversation_id`, `sequence_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Spring AI模型上下文窗口表';

CREATE TABLE IF NOT EXISTS `ai_conversation` (
  `conversation_id` char(36) NOT NULL COMMENT '会话ID，UUIDv7',
  `user_id` char(36) NOT NULL COMMENT '会话归属用户ID',
  `title` varchar(128) NOT NULL DEFAULT '' COMMENT '会话标题',
  `provider` varchar(64) NOT NULL DEFAULT '' COMMENT '模型服务提供方',
  `model` varchar(128) NOT NULL DEFAULT '' COMMENT '模型名称',
  `system_prompt` text NOT NULL COMMENT '会话系统提示词',
  `message_count` int unsigned NOT NULL DEFAULT 0 COMMENT '前端可见消息数量',
  `last_message_at` bigint unsigned NOT NULL COMMENT '最后消息时间，Unix毫秒',
  `status` varchar(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE ARCHIVED',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`conversation_id`),
  KEY `idx_ai_conversation_user_updated` (`user_id`, `updated_at`),
  KEY `idx_ai_conversation_user_last_message` (`user_id`, `last_message_at`),
  KEY `idx_ai_conversation_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI会话主表';

CREATE TABLE IF NOT EXISTS `ai_conversation_message` (
  `message_id` char(36) NOT NULL COMMENT '消息ID，UUIDv7',
  `conversation_id` char(36) NOT NULL COMMENT '会话ID',
  `user_id` char(36) NOT NULL COMMENT '会话归属用户ID',
  `prompt_record_id` char(36) NOT NULL COMMENT '关联Prompt记录ID',
  `sequence_no` int unsigned NOT NULL COMMENT '会话内消息序号',
  `role` varchar(32) NOT NULL COMMENT '消息角色：SYSTEM USER ASSISTANT TOOL',
  `content` longtext NOT NULL COMMENT '消息内容',
  `content_type` varchar(32) NOT NULL DEFAULT 'TEXT' COMMENT '内容类型',
  `metadata` json DEFAULT NULL COMMENT '消息扩展元数据',
  `message_status` varchar(32) NOT NULL DEFAULT 'COMPLETED' COMMENT '消息状态：STREAMING COMPLETED CANCELLED FAILED',
  `error_code` varchar(64) NOT NULL DEFAULT '' COMMENT '稳定错误码',
  `error_message` varchar(512) NOT NULL DEFAULT '' COMMENT '安全错误摘要',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  PRIMARY KEY (`message_id`),
  UNIQUE KEY `uk_ai_message_sequence` (`conversation_id`, `sequence_no`, `deleted`),
  KEY `idx_ai_message_user_conversation` (`user_id`, `conversation_id`),
  KEY `idx_ai_message_prompt_record` (`prompt_record_id`),
  KEY `idx_ai_message_status` (`conversation_id`, `message_status`),
  KEY `idx_ai_message_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI会话完整消息表';

CREATE TABLE IF NOT EXISTS `ai_prompt_record` (
  `prompt_record_id` char(36) NOT NULL COMMENT 'Prompt记录ID，UUIDv7',
  `conversation_id` char(36) NOT NULL COMMENT '会话ID',
  `user_id` char(36) NOT NULL COMMENT '调用用户ID',
  `provider` varchar(64) NOT NULL DEFAULT '' COMMENT '模型服务提供方',
  `model` varchar(128) NOT NULL DEFAULT '' COMMENT '模型名称',
  `request_messages` json NOT NULL COMMENT '实际送模完整消息数组',
  `prompt_summary` varchar(2048) NOT NULL DEFAULT '' COMMENT '截断脱敏后的Prompt摘要',
  `prompt_truncated` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '摘要是否被截断：1是 0否',
  `response_content` longtext NOT NULL COMMENT '模型响应文本',
  `response_metadata` json DEFAULT NULL COMMENT '模型响应元数据',
  `prompt_tokens` int unsigned DEFAULT NULL COMMENT '输入Token数',
  `completion_tokens` int unsigned DEFAULT NULL COMMENT '输出Token数',
  `total_tokens` int unsigned DEFAULT NULL COMMENT '总Token数',
  `finish_reason` varchar(64) NOT NULL DEFAULT '' COMMENT '模型结束原因',
  `status` varchar(32) NOT NULL DEFAULT 'PROCESSING' COMMENT '状态：PROCESSING SUCCESS FAILED',
  `error_type` varchar(256) NOT NULL DEFAULT '' COMMENT '错误类型',
  `error_message` text DEFAULT NULL COMMENT '错误信息',
  `cost_ms` bigint unsigned NOT NULL DEFAULT 0 COMMENT '调用耗时毫秒',
  `track_id` varchar(64) NOT NULL DEFAULT '' COMMENT '链路追踪ID',
  `created_at` bigint unsigned NOT NULL COMMENT '创建时间，Unix毫秒',
  `updated_at` bigint unsigned NOT NULL COMMENT '更新时间，Unix毫秒',
  `created_by` char(36) NOT NULL DEFAULT '' COMMENT '创建人ID',
  `updated_by` char(36) NOT NULL DEFAULT '' COMMENT '更新人ID',
  `deleted` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `remark` varchar(512) NOT NULL DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`prompt_record_id`),
  KEY `idx_ai_prompt_conversation` (`conversation_id`, `created_at`),
  KEY `idx_ai_prompt_user` (`user_id`, `created_at`),
  KEY `idx_ai_prompt_track_id` (`track_id`),
  KEY `idx_ai_prompt_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AI模型完整Prompt调用记录表';
